apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
spec:
  containers:
  - name: web-server
    image: nginx:latest
    ports:
    - containerPort: 80
  initContainers:
  - name: init-container
    image: busybox:latest
    command: ['sh', '-c', 'wget -O /usr/share/nginx/html/index.html http://example.com/index.html']
