---
- name: Setup Web Server and Database
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Copy Website Files
      copy:
        src: "/home/ec2-user" 
        dest: /usr/share/nginx/html
      notify: Restart Nginx

    - name: Install SQLite
      yum:
        name: sqlite
        state: present

    - name: Create SQLite Database
      command: sqlite3 /usr/share/nginx/html/database.db ".read {{ playbook_dir }}/schema.sql"
      ignore_errors: yes 

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

